[build-system]
requires = ["setuptools", "zstandard", "enlighten", "pycryptodome", "requests"]

[project]
name = 'nstools'
requires-python = ">=3.10"
version = "1.0.7"

[tool.setuptools]
packages = ["Fs", "lib", "nut"]
